version: '3.8'
services:
  mypgsql-service:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_DB=mylibrary
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypass
    ports:
      - '5434:5432'
    volumes:
      - mypgsql-data:/var/lib/postgresql/data
volumes:
  mypgsql-data:
    driver: local



# If needed:
# https://stackoverflow.com/questions/38249434/docker-postgres-failed-to-bind-tcp-0-0-0-05432-address-already-in-use